{ pkgs, ... }:
{
  # Add backup extension to automatically back up conflicting files
  home-manager.backupFileExtension = "backup";

  home-manager.users.gaurav =
    { ... }:
    {
      # Install VLC package
      home.packages = [ pkgs.vlc ];

      # Create VLC config file manually
      xdg.configFile."vlc/vlcrc" = {
        text = ''
          # VLC Configuration File
          # Generated by NixOS configuration
          # General settings
          qt-continue=2
          video-title-show=0
          volume-save=1
          qt-auto-raise=0
          qt-fs-controller=0
          qt-recentplay=1
          sout-keep=1
          input-fast-seek=1
          # Hardware acceleration settings
          avcodec-hw=any
          ffmpeg-hw=1
          # Audio settings
          audio-replay-gain-mode=track
          audio-desync=0
          # Interface settings
          qt-privacy-ask=0
          metadata-network-access=1
          # Performance settings
          clock-jitter=0
          clock-synchro=0
          # Video settings
          video-deco=1
          video-title-timeout=800
          preferred-resolution=-1
        '';
        force = true; # Force overwrite existing files
      };

      # Create VLC shortcuts/hotkeys config if needed
      xdg.configFile."vlc/vlc-qt-interface.conf" = {
        text = ''
          [MainWindow]
          ShowRemainingTime=1
          [Preferences]
          geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc3\0\0\0\x19\0\0\a}\0\0\x4\x31\0\0\x3\xc5\0\0\0\x1b\0\0\a{\0\0\x4/\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc5\0\0\0\x1b\0\0\a{\0\0\x4/)
          [RecentsMRL]
          list=@Invalid()
          times=@Invalid()
        '';
        force = true; # Force overwrite existing files
      };
    };
}
