windows:
  - main:
      layout: main-vertical
      panes: [null]
  - nvim:
      layout: main-horizontal
      panes: [nvim]
  - git:
      layout: main-horizontal
      panes: [lazygit]
  - ai:
      layout: main-horizontal
      panes: [opencode]
  - term:
      layout: main-horizontal
      panes: [null, null, null]
