# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  fileSystems."/iso" = {
    device = "/dev/disk/by-uuid/1980-01-01-00-00-00-00";
    fsType = "iso9660";
  };

  fileSystems."/nix/.ro-store" = {
    device = "/iso/nix-store.squashfs";
    fsType = "squashfs";
    options = ["loop"];
  };

  fileSystems."/nix/.rw-store" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  fileSystems."/nix/store" = {
    device = "overlay";
    fsType = "overlay";
  };

  fileSystems."/mnt" = {
    device = "/dev/disk/by-uuid/752798cb-4ce8-4c05-aa66-caa0a3cf4e3b";
    fsType = "ext4";
  };

  fileSystems."/mnt/boot" = {
    device = "/dev/disk/by-uuid/EEE6-836E";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/34e507fe-f7c8-4492-819f-7b679fa05116";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
