# ~/.config/starship.toml

add_newline = false
command_timeout = 1000

format = """$character$directory$custom"""

[character]
success_symbol = '[ ➜](bold green) '
error_symbol = '[ ➜](bold red) '

[directory]
format = '[$path]($style) '
style = 'bold cyan'
truncation_length = 3
home_symbol = '~'

# Custom git info
[custom.git_info]
command = '''
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    branch=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
    if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
        printf "\033[1;34mgit:(\033[0;31m%s\033[1;34m) \033[1;33m✘ \033[0m " "$branch"
    else
        printf "\033[1;34mgit:(\033[0;31m%s\033[1;34m)\033[0m " "$branch"
    fi
fi
'''
when = 'git rev-parse --is-inside-work-tree >/dev/null 2>&1'
format = '$output'
shell = ['sh']

[git_branch]
disabled = true
[git_status]
disabled = true
[package]
disabled = true
[nodejs]
disabled = true
[python]
disabled = true
[ruby]
disabled = true
[aws]
disabled = true
[docker_context]
disabled = true
[nix_shell]
disabled = true
